import type { ToolServer } from "./types.js";
import { registerSendCodeToRevitTool } from "./send_code_to_revit.js";
import { registerSendCodeToRevitSafeTool } from "./send_code_to_revit_safe.js";
import { registerGetRevitSessionContextTool } from "./get_revit_session_context.js";
import { registerGetActiveViewContextTool } from "./get_active_view_context.js";
import { registerListOpenViewsTool } from "./list_open_views.js";
import { registerActivateViewTool } from "./activate_view.js";
import { registerCloseViewTool } from "./close_view.js";
import { registerGetUiStateTool } from "./get_ui_state.js";
import { registerFindElementsTool } from "./find_elements.js";
import { registerOpenExistingPlanForElementLevelTool } from "./open_existing_plan_for_element_level.js";
import { registerFocusElementsTool } from "./focus_elements.js";
import { registerSectionBoxElementsTool } from "./section_box_elements.js";
import { registerCreate3DViewForElementsTool } from "./create_3d_view_for_elements.js";
import { registerExportRevitCoordinationImageTool } from "./export_revit_coordination_image.js";
import { registerExportRevitViewImageTool } from "./export_revit_view_image.js";
import { registerShowElementInPlanAnd3DTool } from "./show_element_in_plan_and_3d.js";
import { registerSmartFocusElementsTool } from "./smart_focus_elements.js";
import { registerInspectElementsTool } from "./inspect_elements.js";
import { registerInspectSheetTextTool } from "./inspect_sheet_text.js";
import { registerInspectSchedulesTool } from "./inspect_schedules.js";
import { registerInspectParameterSchemaTool } from "./inspect_parameter_schema.js";
import { registerSetElementParameterTool } from "./set_element_parameter.js";
import { registerSetScheduleCellsTool } from "./set_schedule_cells.js";
import { registerSetScheduleCellsByTextTool } from "./set_schedule_cells_by_text.js";
import { registerListRevitInstancesTool } from "./list_revit_instances.js";
import { registerGetRevitMcpStatusTool } from "./get_revit_mcp_status.js";
import { wrapServerWithTelemetry } from "../utils/telemetry.js";

export async function registerTools(server: ToolServer) {
    const telemetryServer = wrapServerWithTelemetry(server);
    registerListRevitInstancesTool(telemetryServer);
    registerGetRevitMcpStatusTool(telemetryServer);
    registerSendCodeToRevitTool(telemetryServer);
    registerSendCodeToRevitSafeTool(telemetryServer);
    registerGetRevitSessionContextTool(telemetryServer);
    registerGetActiveViewContextTool(telemetryServer);
    registerListOpenViewsTool(telemetryServer);
    registerActivateViewTool(telemetryServer);
    registerCloseViewTool(telemetryServer);
    registerGetUiStateTool(telemetryServer);
    registerFindElementsTool(telemetryServer);
    registerOpenExistingPlanForElementLevelTool(telemetryServer);
    registerFocusElementsTool(telemetryServer);
    registerSectionBoxElementsTool(telemetryServer);
    registerCreate3DViewForElementsTool(telemetryServer);
    registerExportRevitViewImageTool(telemetryServer);
    registerExportRevitCoordinationImageTool(telemetryServer);
    registerShowElementInPlanAnd3DTool(telemetryServer);
    registerSmartFocusElementsTool(telemetryServer);
    registerInspectElementsTool(telemetryServer);
    registerInspectSheetTextTool(telemetryServer);
    registerInspectSchedulesTool(telemetryServer);
    registerInspectParameterSchemaTool(telemetryServer);
    registerSetElementParameterTool(telemetryServer);
    registerSetScheduleCellsTool(telemetryServer);
    registerSetScheduleCellsByTextTool(telemetryServer);
    console.error("Registered 26 Revit MCP tools");
}
