export type * from "./generated/envelope.js";
export {
  parseRbpFrame,
  RBP_MAX_CONTROL_FRAME_BYTES,
  RBP_MAX_DOC_CONTEXT_FRAME_BYTES,
  RBP_MAX_INLINE_RESULT_BYTES,
  RBP_MAX_INVOCATION_PARAMS_BYTES,
  RbpFrameError,
  type RbpFrameErrorCode,
} from "./parseFrame.js";
export {
  canonicalizeJson,
  makeBatchDigest,
  makeParamsDigest,
  type BatchDigestInput,
  type BatchDigestStep,
  type JsonValue,
} from "./paramsDigest.js";
export {
  RBP_RECONNECT_CAP_MS,
  RBP_RECONNECT_FACTOR,
  RBP_RECONNECT_INITIAL_MS,
  RBP_RECONNECT_RESET_AFTER_STEADY_MS,
  reconnectBackoffLimitMs,
  reconnectFullJitterDelayMs,
  shouldResetReconnectBackoff,
} from "./reconnectBackoff.js";
export {
  acceptInboundData,
  applyCumulativeAck,
  closeDispatchWindow,
  createDispatchWindowLedger,
  createRbpSequenceState,
  dataEnvelopeImmutableDigest,
  openDispatchWindow,
  queueOutboundData,
  RBP_MAX_SAFE_SEQUENCE,
  retransmitOutbox,
  sequenceRenewalStatus,
  type AcceptedInboundData,
  type AckResult,
  type DataEnvelopeSnapshot,
  type DispatchWindowEntry,
  type DispatchWindowLedger,
  type InboundDataResult,
  type OpenDispatchWindowResult,
  type OutboundDataDraft,
  type QueueOutboundResult,
  type RbpSequenceState,
  type RetainedOutboundData,
} from "./sequenceState.js";
export {
  createConnectionLifecycle,
  createSessionLifecycle,
  RBP_HEARTBEAT_DEGRADED_AFTER_MS,
  RBP_HEARTBEAT_DISCONNECTED_AFTER_MS,
  transitionConnection,
  transitionSession,
  type ConnectionEvent,
  type ConnectionLifecycleState,
  type ConnectionPhase,
  type ConnectionTransition,
  type OpeningFailureClass,
  type RetryDecision,
  type RetryPauseReason,
  type SessionEvent,
  type SessionLifecycleState,
  type SessionPhase,
  type SessionTransition,
} from "./connectionState.js";
export {
  createReceivedJournalRecord,
  decideAtomicBatchRedelivery,
  decideJournalRedelivery,
  handleJournalSessionUnregister,
  journalRecordIsIntact,
  makeJournalBindingDigest,
  makeJournalTerminalOutcomeDigest,
  markJournalExecuting,
  markJournalIndeterminate,
  planAtomicFalseBatchRedelivery,
  recordJournalTerminal,
  requestJournalCancellation,
  validateAtomicFalseBatchStatuses,
  type AtomicBatchJournalRecord,
  type AtomicBatchBinding,
  type AtomicBatchRedeliveryDecision,
  type AtomicFalseBatchPlan,
  type AtomicFalseBatchPlanResult,
  type AtomicFalseBatchPlanStep,
  type BatchIdentityFault,
  type BatchStepStatus,
  type CancellationDecision,
  type InvocationJournalBinding,
  type InvocationJournalRecord,
  type InvocationJournalState,
  type JournalPolicyBinding,
  type JournalRedeliveryDecision,
  type KnownTerminalJournalState,
  type TerminalJournalOutcome,
  type UnregisterJournalDecision,
} from "./journalState.js";
export {
  authorizeMutationDispatch,
  conflictingMutationHolds,
  createMutationHoldLedger,
  installMutationHolds,
  isOriginRedeliveryExempt,
  makeMutationHoldId,
  mutationScopeKey,
  mutationScopesConflict,
  recordLateTerminalEvidence,
  recordVerificationEvidence,
  recoveryClearanceForHold,
  resolveMutationHold,
  type AuthorizeMutationResult,
  type HoldEvidenceAttempt,
  type HoldEvidenceConclusion,
  type HoldResolution,
  type HoldResolutionDecision,
  type InstallMutationHoldsResult,
  type MutationHold,
  type MutationHoldLedger,
  type MutationHoldState,
  type RecordHoldEvidenceResult,
  type ResolveMutationHoldResult,
  type UncertainMutation,
} from "./mutationHold.js";
export {
  classifyMutationError,
  knownNotDispatched,
  MUTATION_OUTCOME_SCHEMA,
  parseAddinMutationOutcomeEvidence,
  validateMutationOutcomeEvidence,
  type AddinMutationOutcomeEvidence,
  type DispatchState,
  type EffectState,
  type MutationErrorDisposition,
  type MutationOutcomeEvidence,
  type TransactionMode,
} from "./mutationOutcome.js";
export {
  appendStreamChunk,
  createStreamAssembler,
  finalizeStreams,
  RBP_MAX_ARTIFACTS_PER_INVOCATION,
  RBP_MAX_DECODED_CHUNK_BYTES,
  RBP_MAX_RECONSTRUCTED_INVOCATION_BYTES,
  type AppendStreamChunkResult,
  type ArtifactReference,
  type CompletedStream,
  type FinalizeStreamsResult,
  type RbpStreamChunk,
  type ResultStreamDescriptor,
  type RetainedStreamChunk,
  type StreamAssemblerState,
  type StreamAssembly,
  type TerminalStreamManifest,
} from "./streamAssembler.js";
export { validateRbpEnvelope, rbpEnvelopeErrors } from "./validateEnvelope.js";

/** Numeric major carried by negotiated RBP/1 data envelopes. */
export const RBP_PROTOCOL_VERSION = 1 as const;
/** Canonical O1 specification identity; freeze acceptance is recorded separately. */
export const RBP_SPEC_VERSION = "1.0" as const;

export function makeIdempotencyKey(rsid: string, invocationId: string): string {
  if (rsid.length === 0 || invocationId.length === 0) {
    throw new Error("rsid and invocationId are required");
  }

  return `${rsid}/${invocationId}`;
}
